Adaptive BAL
apax-hub/apax pull request #330
Opened 2024-08-26 17:15 UTC by M-R-Schaefer

This PR adds a few features:
- adaptive BAL which selects up to a minimum inter sample distance instead of a fixed number of samples.
- fixed force features for BAL
- added full gradient features with random projections to the available feature maps
- new visualizations to the BAL IPS node

2024-09-12 10:10 UTC, M-R-Schaefer commented
pre-commit.ci autofix

2024-09-17 12:03 UTC, Tetracarbonylnickel requested changes

2024-09-17 13:00 UTC, M-R-Schaefer commented on apax/bal/feature_maps.py
> +                raise ValueError(f"unknown strategy: {self.strategy}")
the implementations of the different options is 19 lines of code, I don't think further abstraction is required.

2024-09-17 13:43 UTC, Tetracarbonylnickel approved these changes

2024-09-17 13:53 UTC, merged