AdEMAmix, Gradient clipping
apax-hub/apax pull request #342
Opened 2024-09-10 21:00 UTC by M-R-Schaefer

Moved optimizers to separate submodule and added AdEMAmix opt.
Added gradient clipping,

2024-09-10 21:00 UTC, M-R-Schaefer commented
pre-commit.ci autofix

2024-09-17 12:44 UTC, Tetracarbonylnickel requested changes

2024-09-17 12:44 UTC, Tetracarbonylnickel commented on apax/config/train_config.py
> +    gradient_clipping: NonNegativeFloat, default = 1000.0
default is 10_000

2024-09-17 12:44 UTC, Tetracarbonylnickel commented on apax/optimizer/get_optimizer.py
> +    gradient_clipping=1000.0,
here its 1000 again

2024-09-17 13:44 UTC, Tetracarbonylnickel approved these changes

2024-09-17 13:53 UTC, merged